version: '3'
services:
  db:
    build: Dockerfile.db
    container_name: 'db'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    volumes:
      - psql_data:/var/lib/postgresql/data
      
  app:
    tty: true
    build: Dockerfile
    container_name: 'app'
    command: ""
    volumes:
      - ./:/
      - node_modules:/frontend/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - db
      
volumes:
  psql_data:
  node_modules:
