version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      -  "13306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  app:
    tty: true
    container_name: app
    build:　　 　
      context: ./app
    volumes:
      - ../../..:/var/www/html
    ports:
      - "19000:9000"
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      -  "8080:80"
    volumes:
      - ../../..:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      -  app
      -  mysql