name: PHP Code Quality

on:
  pull_request:
    paths:
      - 'front/**'

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Cache Packages
        uses: actions/cache@v2
        id: cache-packages
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install Packages
        if: steps.cache-packages.outputs.cache-hit != 'true'
        working-directory: ./front
        run: yarn --frozen-lockfile
      - name: Run Lint
        working-directory: ./front
        run: yarn eslint:check

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Cache Packages
        uses: actions/cache@v2
        id: cache-packages
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install Packages
        if: steps.cache-packages.outputs.cache-hit != 'true'
        working-directory: ./front
        run: yarn --frozen-lockfile
      - name: Check Format 
        working-directory: ./front
        run: yarn prettier:check
