name: JS Code Quality

on:
  pull_request:
    paths:
      - 'front/**'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Packages
        working-directory: ./front
        run: yarn --frozen-lockfile
      - name: Run Lint
        working-directory: ./front
        run: yarn eslint:check

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Packages
        working-directory: ./front
        run: yarn --frozen-lockfile
      - name: Check Format 
        working-directory: ./front
        run: yarn prettier:check
